teams_dict =[{'name':'ATLÉTICO MINEIRO SAF'},
             {'name':'BAHIA'},
             {'name':'BOTAFOGO'},
             {'name':'CEARÁ'},
             {'name':'CORINTHIANS'},
             {'name':'CRUZEIRO SAF'},
             {'name':'FLAMENGO'},
             {'name':'FLUMINENSE'},
             {'name':'FORTALEZA EC SAF'},
             {'name':'GRÊMIO'},
             {'name':'INTERNACIONAL'},
             {'name':'JUVENTUDE'},
             {'name':'MIRASSOL'},
             {'name':'PALMEIRAS'},
             {'name':'RED BULL BRAGANTINO'},
             {'name':'SANTOS FC'},
             {'name':'SÃO PAULO'},
             {'name':'SPORT RECIFE'},
             {'name':'VASCO DA GAMA S.A.F.'},
             {'name':'VITÓRIA'}]

